CREATE TABLE GROUPS (
  ID BIGINT AUTO_INCREMENT NOT NULL,
   NAME VARCHAR(255),
   SCHOOL_YEAR INT,
   STUDENT_AMOUNT INT NOT NULL,
   PROGRAM VARCHAR(255),
   SHIFT VARCHAR(255),
   CONSTRAINT PK_GROUP PRIMARY KEY (ID)
);