CREATE TABLE TEACHER (
                         ID BIGINT GENERATED BY DEFAULT AS IDENTITY,
                         NAME CHARACTER VARYING(85),
                         SURNAME CHARACTER VARYING(120),
                         LOGIN_EMAIL CHARACTER VARYING (120),
                         CONTACT_EMAIL CHARACTER VARYING (120),
                         PHONE CHARACTER VARYING (20),
                         WORK_HOURS_PER_WEEK INTEGER,

                         SHIFT CHARACTER VARYING (30),

                         CONSTRAINT TEACHER_PK PRIMARY KEY (ID)
);