INSERT INTO SUBJECT (NAME,DESCRIPTION, CREATED_DATE, MODIFIED_DATE, DELETED) VALUES
    ('Operacinės sistemos','Speciali programinė įranga, užtikrinanti vartotojo sąsają ir kompiuterio techninės įrangos, taikomųjų programų bei duomenų valdymą. Moderniausios operacinės sistemos sudaro galimybę dirbti daugeliui vartotojų vienu metu daugialypėje aplinkoje, užtikrina bylų (failų) apsaugą, turi daug kitų naudingų savybių. Dauguma operacinių sistemų yra pirma programinė įranga, kurią pradeda vykdyti įjungtas kompiuteris.','2023-01-01 00:36:54.344','2023-02-18 00:36:54.344', FALSE),
    ('Duomenų bazės','Organizuotas (susistemintas, metodiškai sutvarkytas) duomenų rinkinys, kuriuo galima individualiai naudotis elektroniniu ar kitu būdu. Nors terminas kilo kompiuterių pramonėje, dabartinės vartojimo prasmės ribos praplėstos ir EU Database Directive (kurianti duomenų bazių intelektinės nuosavybės teises) apima ir neelektronines rūšis.','2023-01-01 00:36:54.344','2023-02-16 00:36:54.344', FALSE),
    ('Reactas','Tiesiog reaktyvu. Be galo įdomi paskaita skatinanti mokytis patiems ir susikoncentruoti į pačius netikėčiausius dalykus.','2023-01-01 00:36:54.344','2023-02-12 00:36:54.344', FALSE),
    ('Matematika','Mokslas, tiriantis struktūrų, kitimų ir erdvių modelius. Formaliai matematika yra aksiomomis apibrėžtų abstrakčių struktūrų nagrinėjimas, naudojant logiką ir matematinius žymėjimus. Matematikai tyrinėja struktūras, kurios turi atitikmenis kituose tiksliuosiuose moksluose, pavyzdžiui, fizikoje, taip pat apibrėžia naujas struktūras.','2023-01-01 00:36:54.344','2023-02-20 00:36:54.344', FALSE),
    ('Fizika','Gamtos mokslas, tiriantis visas materijos formas:[2] nuo submikroskopinių dalelių, iš kurių sudarytos visos įprastinės medžiagos (dalelių fizika), iki visos materialios Visatos elgesio (kosmologija).','2023-01-01 00:36:54.344','2023-02-28 00:36:54.344', FALSE),
    ('Filosofija','Mokslas apie bendriausius gamtos, visuomenės ir mąstymo dėsningumus, tiriantis tikrovės ir esminius žmogiškosios būties ir patirties aspektus, tokius kaip egzistencija, protavimas, žinojimas, gėris ir vertybės, sąmonė ir kalba.','2023-01-01 00:36:54.344','2023-01-08 00:36:54.344', FALSE),
    ('Psichologija','Socialinis mokslas, tiriantis psichinius reiškinius, jų kilmę, raidą, reiškimosi formas ir mechanizmus, psichikos faktus, nustatantis dėsnius ir kuriantis jų aiškinimo sistemas.[','2023-01-01 00:36:54.344','2023-01-08 04:36:54.344', FALSE),
    ('Braižyba','Sisciplina, nagrinėjanti brėžinių braižymo ir jų skaitymo taisykles, viena iš vaizduojamojo meno rūšių. Objekto vaizdas, nubrėžtas pagal tam tikras taisykles braižybos įrankiais, pasirinktu masteliu vad. brėžiniu. Pagal brėžinį galima spręsti apie daikto ar jo dalies sandarą, matmenis bei formą. Be brėžinių negalėtų išsiversti inžinieriai, įv. technikos kūrėjai ir konstruotojai, architektai.','2023-01-01 00:36:54.344','2023-02-17 00:36:54.344', FALSE),
    ('Meno istorija','Tradiciškai laikoma, kad istorijos objektas yra dokumentuota žmonijos patirtis, todėl laikotarpis iki rašytinių šaltinių atsiradimo dažnai vadinamas priešistore, arba proistore (įvairiose šalyse raštas atsirado skirtingu laiku, todėl vieningos priešistorės – istorijos „ribos“ nėra). ','2023-01-01 00:36:54.344','2023-02-12 00:36:54.344', FALSE),
    ('Etika','Moderniosios eros etines teorijas iš esmės galima suskirstyti į pasekmistines, kaip Džiono Stiuarto Milio ir Džeremio Bentamo utilitarizmo teorijos, bei deontologines, kurias įkūnija Imanuelio Kanto darbai.','2023-01-01 00:36:54.344','2023-02-11 00:36:54.344', FALSE),
        ('Tikyba','Tikybos mokymas yra konfesinis – jį vykdo Bažnyčios įgalioti asmenys, remdamiesi Katalikų bažnyčios doktrina ir Šventojo Sosto rekomendacijomis. Šio mokymo tikslas – padėti mokiniams pažinti krikščioniškas vertybes ir paskatinti jomis grįsti savo asmeninį bei bendruomeninį gyvenimą. Itin akcentuojamas etinių, egzistencinių, socialinių, kultūrinių klausimų svarstymas tikėjimo šviesoje.','2023-01-01 00:36:54.344','2023-02-12 00:56:54.344', FALSE),
        ('Dailė','Meno rūšis, skirstoma į vaizduojamąją (tapyba, grafika ir skulptūra) ir taikomąją – dekoratyvinę (keramika, tekstilė, oda, amatai, liaudies meistrų dirbiniai ir kt.). Skirtingai nuo kitų meno rūšių (muzikos, teatro, literatūros, kino) dailės kūriniai paprastai turi materialią – tūrinę formą.','2023-01-01 00:36:54.344','2023-02-11 00:36:34.344', FALSE),
        ('Sociologija','Socialinis mokslas, tiriantis ir aprašantis visuomenės struktūrines ir funkcines sąsajas.[1] Tai yra socialinis mokslas, tiriantis ne specifines temas (kaip, pvz., politikos mokslas arba ekonomika), bet siekiantis naudojant sociologinius metodus ištirti socialinį bendruomenių ir visuomenės gyvenimą.','2023-01-01 00:36:54.344','2023-02-04 00:36:54.344', FALSE),
        ('Vaidyba','Vaidyba – unikali, teatro krypties studijų programa, orientuota į vizualųjį teatrą. Vizualusis teatras – XX –XXI a. sankirtoje susiformavusi ir išryškėjusi teatro forma, jungianti dramos teatro patirtį su vaizduojamuoju menu.','2023-01-01 00:36:54.344','2023-02-02 00:36:54.344', FALSE),
        ('Prancūzų kalba','nu wow fantastika','22023-01-01 00:36:54.344','2023-02-01 00:36:54.344', TRUE),
        ('Chemija','Mokslas, tiriantis cheminius elementus bei jų sudaromų vieninių ir sudėtinių medžiagų struktūrą, savybes ir kitimus, vykstančius cheminių reakcijų metu. Pagrindinis chemijos uždavinys – suprasti medžiagos prigimtį. Pagrindinis būdas, taikomas šio uždavinio sprendimui – medžiagos skaidymas į paprastesnius komponentus ir naujų medžiagų sintezė. Taip buvo sukurta daug medžiagų, kurių negalima sutikti gamtoje.','2023-01-01 00:36:54.344','2023-02-06 00:36:54.344', TRUE),
            ('Lipdymas iš molio','Jei pas Jus namuose šilta, oro temperatūra aukštesnė nei 16 laipsnių, rekomenduojame molio nepalikti nesandarioje pakuotėje. Molis džiūsta, praranda savo plastiškumą ir tuomet reikės jį minkyti drėkinant. O tai nėra labai švarus ir lengvas darbas. Daug lengviau, baigus darbą, jį uždengti, įvyniojant į plastiko pakuotę.','2023-01-01 00:36:54.344','2023-02-07 00:36:54.344', TRUE),
            ('Fotografija','Vaizdų išsaugojimo technologija, naudojant mechaninius, cheminius ar skaitmeninius metodus. Žodis kilęs iš graikų kalbos žodžių φως phos („šviesa“) bei γραφις graphis („teptukas“), kurie kartu reiškia piešimas šviesa. Šis terminas anglų ir vokiečių kalboje pradėtas vartoti 1839 m. vasarį.','2023-01-01 00:36:54.344','2023-02-10 00:36:54.344', TRUE),
            ('Sportas','Pagal tam tikras taisykles organizuojama žmonių veikla, derinant fizinius ir intelektinius gebėjimus, skirta varžymuisi, laisvalaikio praleidimui, įvairių įgūdžių lavinimui, taip pat pasiruošimas šiai veiklai ir to pasiruošimo metu atsirandantys tarpusavio santykiai. Sportu siekiama varžytis, stiprinti sveikatą, gauti moralinį ir materialinį pasitenkinimą, taip pat atlygį, išreikšti save, tobulintis, siekti garbės ir šlovės.','2023-01-01 00:36:54.344','2023-02-11 00:36:54.344', TRUE),
            ('Geologija','Geologija – tai mokslas apie Žemę, jos uolienas, iškasenas, požeminį vandenį, inžinerines geologines sąlygas ir kt. Šios paklausios specialybės atstovai tiria Žemės gelmes, jų panaudojimo galimybes, ieško naudingųjų iškasenų, energijos šaltinių, mokosi kaip vertinti požeminio vandens išteklius ir aplinkos inžinerines geologines sąlygas.','2023-01-01 00:36:54.344','2023-02-10 00:36:54.344', TRUE),
            ('Geografija','Mokslas, kuris tiria Žemės fizinę erdvę ir paviršiaus vystimasi, taip pat jos fizines savybes bei erdvę ir vietą, kurioje gyvena ir prekiauja žmonės','2023-01-01 00:36:54.344','2023-02-09 00:36:54.344', TRUE);


