INSERT INTO program (name, description, created_date, modified_date, DELETED)
VALUES ('Laivo virėjo modulinė profesinio mokymo programa', 'Laivo virėjo modulinė profesinio mokymo programa yra skirta kvalifikuotam laivo virėjui parengti, kuris gebėtų savarankiškai organizuoti jūrininkų ir kitų asmenų maitinimą laive, gaminti ir patiekti patiekalus.', '2023-01-12 19:36:54.344', '2023-01-12 19:36:54.344', FALSE),
       ('Policininko modulinė profesinio mokymo programa', 'Policininko modulinė profesinio mokymo programa skirta kvalifikuotam pirminės grandies policijos pareigūnui (policininkui), kuris gebėtų operatyviai reaguoti į gaunamą informaciją apie nusikalstamas veikas ir administracinius nusižengimus, užtikrinti viešąją tvarką, asmens, visuomenės ir eismo saugumą, tinkamai bendrauti su interesantais, ir kitais asmenimis, parengti.', '2023-01-12 19:36:54.447', '2023-01-12 19:36:54.451', FALSE),
       ('Kirpėjo modulinė profesinio mokymo programa', 'Kirpėjo modulinė profesinio mokymo programa skirta kvalifikuotam darbuotojui parengti, kuris gebėtų savarankiškai atlikti trumpalaikį plaukų sušukavimą, kirpti ir dažyti plaukus bei modeliuoti šukuosenas.', '2023-01-12 19:36:54.344', '2023-01-12 19:36:54.458', FALSE),
       ('Virėjo modulinė profesinio mokymo programa', 'Virėjo modulinė profesinio mokymo programa yra skirta kvalifikuotam virėjui parengti, kuris gebėtų, prižiūrint aukštesnės kvalifikacijos darbuotojui, parinkti maisto produktus ir žaliavas, atlikti jų pirminį apdorojimą, gaminti nesudėtingos technologijos pusgaminius ir patiekalus.', '2023-01-12 19:36:54.447', '2023-01-12 19:36:54.344', FALSE),
       ('Grimuotojo modulinė profesinio mokymo programa', 'Grimuotojo modulinė profesinio mokymo programa skirta kvalifikuotam darbuotojui parengti, kuris gebėtų savarankiškai kurti personažo šukuoseną, kurti ir įgyvendinti charakterinį grimą.', '2023-01-12 19:36:54.458', '2023-01-12 19:36:54.451', FALSE),
       ('Baleto artisto modulinė profesinio mokymo programa', 'Baleto artisto modulinė profesinio mokymo programa skirta sudaryti galimybes įgyti profesines kompetencijas atlikti klasikinį, duetinį, charakterinį šokį, šiuolaikinio ir modernaus šokio elementus, istorinius šokius, įvaldyti aktorinį meistriškumą ir atlikti repertuarą.', '2023-01-12 19:36:54.344', '2023-01-12 19:36:54.451', FALSE),
       ('Žiniatinklio programuotojo modulinė profesinio mokymo programa', 'Modulinės programos tikslas – parengti kvalifikuotą žiniatinklio programuotoją, gebantį dirbti įmonėse, kurios specializuojasi internetinių puslapių ir jiems skirtų taikomųjų programėlių kūrime. Modulinės programos paskirtis - sudaryti galimybes įgyti profesines kompetencijas kvalifikuotam žiniatinklio programuotojui, turinčiam fundamentalių žinių apie pagrindines programavimo kalbas, gebančiam jas pritaikyti projektuojant.', '2023-01-12 19:36:54.458', '2023-01-12 19:36:54.344', FALSE),
       ('Multimedijos techniko modulinė profesinio mokymo programa', 'Multimedijos techniko modulinė profesinio mokymo programa skirta kvalifikuotam multimedijos technikui parengti, kuris gebėtų savarankiškai kurti bei redaguoti dvimatės ir trimatės grafikos produktus, kurti ir redaguoti animacijos produktus, kurti, montuoti bei redaguoti vaizdo ir garso produktus, kurti skaitmeninės komunikacijos kanalus ir publikuoti vaizdo bei garso produktus.', '2023-01-12 19:36:54.447', '2023-01-12 19:36:54.458', FALSE),
       ('Mūrininko-betonuotojo programa', 'Mūrininko–betonuotojo padėjėjo modulinė profesinio mokymo programa skirta kvalifikuotam mūrininko padėjėjui ir betonuotojo padėjėjui parengti, kuris gebėtų, vadovaujant aukštesnės kvalifikacijos darbuotojui ir jam prižiūrint darbų kokybę, vykdyti bendrąsias veiklas statybos objekte, mūryti konstrukcijas ir jas remontuoti, paruošti betoną ir armatūrą, montuoti ir betonuoti konstrukcijas.', '2023-01-12 19:36:54.451', '2023-01-12 19:36:54.458', FALSE),
       ('Audėjo mokymo programa', 'Asmuo, įgijęs audėjo kvalifikaciją, galės dirbti įmonėse, teikiančiose audinių audimo paslaugas, austi rankinėmis audimo staklėmis individualiai. Audėjas savo veikloje vadovaujasi darbuotojų saugos ir sveikatos, ergonomikos, darbo higienos, priešgaisrinės saugos, aplinkosaugos reikalavimais. Dirbama apmetimo mašina, glitavimo įranga, audimo staklėmis ir kita technologinėse audimo operacijose naudojama įranga.', '2023-01-12 19:36:54.458', '2023-01-12 19:36:54.344', FALSE),
       ('Normali', 'normalus dalykai', '2023-01-12 19:36:54.458', '2023-01-12 19:36:54.344', TRUE),
       ('Medienos apdirbėjo profesinė programa', 'Medienos apdirbėjo–dailidės padėjėjo modulinė profesinio mokymo programa skirta kvalifikuotam medienos apdirbėjo padėjėjui ir dailidės padėjėjui parengti, kuris gebėtų padėti aukštesnės kvalifikacijos darbuotojui vykdyti statybos objekte ir medienos apdirbimo įmonėje bendrąsias veiklas; apdirbti medieną ir gaminti medinius gaminius; pakuoti medienos medžiagas, ruošinius, pusfabrikačius.', '2023-01-12 19:36:54.344', '2023-01-12 19:36:54.458', TRUE),
       ('Krosnininko padėjėjo modulinė profesinio mokymo programa', 'Krosnininko padėjėjo modulinė profesinio mokymo programa skirta kvalifikuotam krosnininko padėjėjui parengti, kuris gebėtų, vadovaujant aukštesnės kvalifikacijos darbuotojui ir jam prižiūrint darbų kokybę, savarankiškai vykdyti bendrąsias veiklas statybos objekte, mūryti ir remontuoti kietu kuru kūrenamus šildymo įrenginius (išskyrus katilus), montuoti ir remontuoti kietu kuru kūrenamus šildymo įrenginius (išskyrus katilus).', '2023-01-12 19:36:54.458', '2023-01-12 19:36:54.451', TRUE);
       ('Stogdengio modulinė profesinio mokymo programa', 'Stogdengio modulinė profesinio mokymo programa skirta kvalifikuotam stogdengiui parengti, kuris gebėtų savarankiškai vykdyti bendrąsias veiklas statybos objekte, įrengti bei remontuoti šlaitinį ir plokščią stogus.', '2023-01-12 19:36:54.458', '2023-01-12 19:36:54.447', TRUE);

