INSERT
INTO
  teachers_subjects
  (subject_id, teacher_id)
VALUES
  (CAST(1 AS BIGINT), CAST(1 AS BIGINT)),
  (CAST(1 AS BIGINT), CAST(2 AS BIGINT)),
  (CAST(2 AS BIGINT), CAST(3 AS BIGINT)),
  (CAST(2 AS BIGINT), CAST(4 AS BIGINT)),
  (CAST(3 AS BIGINT), CAST(1 AS BIGINT)),
  (CAST(3 AS BIGINT), CAST(3 AS BIGINT)),
  (CAST(4 AS BIGINT), CAST(2 AS BIGINT)),
  (CAST(4 AS BIGINT), CAST(4 AS BIGINT));